name: API Tests

on: [push, pull_request]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Repository ophalen
      uses: actions/checkout@v3

    - name: Node.js installeren
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Installeer Newman en Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Controleer of de collectie en environment bestaan
      run: |
        if [ ! -f collections/regression_testing.postman_collection.json ]; then
          echo "❌ Collection file ontbreekt!"
          exit 1
        fi
        if [ ! -f environments/rijks.postman_environment.json ]; then
          echo "❌ Environment file ontbreekt!"
          exit 1
        fi

    - name: API-tests draaien
      run: |
        newman run collections/regression_testing.postman_collection.json \
          -e environments/rijks.postman_environment.json \
          --env-var "key=${{ secrets.KEY }}" \
          -r htmlextra \
          --reporter-htmlextra-export reports/test-report.html \
          --verbose

    - name: Newman API-tests uitvoeren
      run: npm run test

    - name: Rapport uploaden
      uses: actions/upload-artifact@v3
      with:
        name: newman-report
        path: reports/test-report.html
