name: API Tests

on: [push, pull_request]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Get Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Scenario-based API-tests with Newman
      if: always()
      run: |
        npx newman run collections/regression_testing.postman_collection.json \
          -e environments/rijks.postman_environment.json \
          --env-var "key=${{ secrets.KEY }}" \
          -r cli,allure \
          --reporter-allure-resultsDir reports/allure-results-1 \
          --folder "scenario_based" \
          --verbose

    - name: Data-driven API-tests with Newman
      if: always()
      run: |
        npx newman run collections/regression_testing.postman_collection.json \
          -e environments/rijks.postman_environment.json \
          --env-var "key=${{ secrets.KEY }}" \
          --iteration-data data/formats_testdata.json \
          -r cli,allure \
          --reporter-allure-resultsDir reports/allure-results-2 \
          --folder "data_driven" \
          --verbose

    - name: Upload Allure results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results-artifact
        path: reports  

  generate-report:
    runs-on: ubuntu-latest
    needs: run-api-tests
    if: always()
    steps:
    - name: Download Allure results
      uses: actions/download-artifact@v3
      with:
        name: allure-results-artifact
        path: reports
 
    - name: Combine Allure Results
      run: |
        mkdir -p allure-results
        cp -r reports/allure-results-1/* allure-results/
        cp -r reports/allure-results-2/* allure-results/

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      #id: allure-report
      with:
        allure_results: allure-results
        #gh_pages: gh-pages
        #allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    # - name: Generate and Publish Allure Report
    #   uses: simple-elf/allure-report-action@master
    #   with:
    #     allure_results: allure-results
    #     allure_history: allure-history
    #     keep_reports: 20
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history

    - name: Post the link to the report
      if: always()
      uses: Sibz/github-status-action@v1
      with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}

    # - name: Deploy Allure Report to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v4
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: allure-history
