name: API Tests

on: [push, pull_request]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Get Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Download vorige Allure-history
      if: always()
      uses: actions/download-artifact@v3
      with:
        name: allure-history
        path: reports/allure-report/history

    - name: Scenario-based API-tests with Newman
      run: |
        npx newman run collections/regression_testing.postman_collection.json \
          -e environments/rijks.postman_environment.json \
          --env-var "key=${{ secrets.KEY }}" \
          -r cli,allure \
          --reporter-allure-resultsDir reports/allure-results-1 \
          --folder "scenario_based" \
          --verbose

    - name: Data-driven API-tests with Newman
      if: always()
      run: |
        npx newman run collections/regression_testing.postman_collection.json \
          -e environments/rijks.postman_environment.json \
          --env-var "key=${{ secrets.KEY }}" \
          --iteration-data data/formats_testdata.json \
          -r cli,allure \
          --reporter-allure-resultsDir reports/allure-results-2 \
          --folder "data_driven" \
          --verbose

    - name:- name: Upload Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results-artifact
        path: reports  

  generate-report:
    runs-on: ubuntu-latest
    needs: run-api-tests
    if: always()
    steps:
    - name: Download Allure results
      uses: actions/download-artifact@v3
      with:
        name: allure-results-artifact
        path: reports
    - name: Combine Allure Results
      run: |
        mkdir -p reports/allure-results
        cp -r reports/allure-results-1/* reports/allure-results/
        cp -r reports/allure-results-2/* reports/allure-results/

    - name: Generate and Publish Allure Report
      uses: simple-elf/allure-report-action@v1.7
      with:
        allure-results: results/allure-results
        allure-history: results/allure-history
        keep-reports: 10
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload nieuwe Allure-history
      uses: actions/upload-artifact@v3
      with:
        name: allure-history
        path: reports/allure-report/history

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHB_TOKEN }}
        publish_dir: ./allure-report
